version: '3.8'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - rb_front_node_modules:/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - WATCHPACK_POLLING=true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: always
  backend:
    build: ./backend
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
      - ./.env:/app/.env
    ports:
      - '8000:8000'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    restart: always
  # pgdb:
  #   image: postgres:latest
  #   restart: always
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   ports:
  #     - '5433:5432'
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.0'
    #       memory: 1024M
  clickhouse:
    image: yandex/clickhouse-server
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - '8123:8123'
      - '9000:9000'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M
    restart: always

volumes:
  rb_front_node_modules:
  db_data:
  clickhouse_data:
