version: '3.8'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - rb_front_node_modules:/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - WATCHPACK_POLLING=true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: always
  backend:
    build: ./backend
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
      - ./.env:/app/.env
    ports:
      - '8000:8000'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    restart: on-failure:5

volumes:
  rb_front_node_modules: